export const ADD_MEETING = 'ADD_MEETING';
export const REMOVE_MEETING = 'REMOVE_MEETING';
export const REMOVE_MEETING_BY_ID = 'REMOVE_MEETING_BY_ID';
export const TOGGLE_MEETING = 'TOGGLE_MEETING';
export const RESET_MEETING = 'RESET_MEETING';
