export const ADD_MEETING = 'ADD_MEETING';
export const REMOVE_MEETING = 'REMOVE_MEETING';
export const REMOVE_MEETING_BY_ID = 'REMOVE_MEETING_BY_ID';

export const ADD_TIMER = 'ADD_TIMER';
export const REMOVE_TIMER = 'REMOVE_TIMER';
export const REMOVE_TIMER_BY_ID = 'REMOVE_TIMER_BY_ID';

export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIMER = 'RESET_TIMER';

export const START_MEETING = 'START_MEETING';
export const STOP_MEETING = 'STOP_MEETING';
export const RESET_MEETING = 'RESET_MEETING';
